A python library is a collection of related modules that contain precompiled code for specific well-defined operations. These libraries simplify programming by providing reusable code, so developers don’t have to write the same functionality repeatedly across different programs.
Here are some key points about python libraries:
- Code Reusability
- Convenience
- Specialized functionality
- Python standard library

1. Homogeneity:
 - NumPy Array: Contains elements of the same data type. It ensures that all data inside the array is consistent.
 - Python List: Can hold different data types (heterogeneous). Elements need not to be of same type.
2. Memory Representation:
 - NumPy Array: Store elements contiguously in memory. Rows of a 2D array have the same number of columns, and a 3D array has consistent rows and columns on each `card`.
 - Python List: Elements are not necessarily contiguous in memory.
3. Element-wise Operations:
 - NumPy Array: Supports element-wise operations (e.g., addition, multiplication) efficiently.
 - Python List: Element-wise operations are not directly possible.
4. Overhead:
 - NumPy Array: Minimal overhead; stores only the data.
 - Python List: Stores additional information (type, reference count) for each element, which can be significantly for large lists.
5. Performance:
 - NumPy Array: Optimize for numerical computations. Faster due to efficient memory layout and vectorized operations.
 - Python List: Slower for numerical tasks due to Python’s interpretation overhead.


In [1]:
import numpy as np
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
arr.shape, arr.size, arr.ndim

((3, 4), 12, 2)

In [2]:
import numpy as np
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
arr[0]

array([1, 2, 3, 4])

In [3]:
import numpy as np
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
arr[2][3]

12

In [4]:
import numpy as np
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if j % 2 != 0:
            print(arr[i][j], end=' ')

2 4 6 8 10 12 

In [7]:
import numpy as np
arr = np.random.rand(3,3)
arr

array([[0.69791295, 0.94182608, 0.15390014],
       [0.0784378 , 0.27328946, 0.51467008],
       [0.32725953, 0.37329035, 0.5341847 ]])

In [8]:
import numpy as np
arr1 = np.random.rand(2,3) #np.random.rand gives random values between the range of 0 and 1
print(f"arr1 : {arr1}")
print()
arr2 = np.random.randn(2) #np.random.randn gives random values whose standard deviation is near to zero
print(f"arr2 : {arr2}")

arr1 : [[0.30185478 0.0598859  0.44808387]
 [0.58004062 0.09172099 0.4169326 ]]

arr2 : [ 1.29285362 -0.00976399]


In [10]:
import numpy as np
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
arr.reshape((2,3,2))
arr.ndim

2

In [1]:
import numpy as np
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [12]:
import numpy as np
matrixA = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
matrixB = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

In [3]:
matrixA * matrixB

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [4]:
np.multiply(matrixA, matrixB) 

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [5]:
np.add(matrixA, matrixB)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [6]:
np.subtract(matrixB, matrixA)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
np.divide(matrixB, matrixA)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
import numpy as np
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
arr.byteswap()

array([[ 72057594037927936, 144115188075855872, 216172782113783808,
        288230376151711744],
       [360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488],
       [648518346341351424, 720575940379279360, 792633534417207296,
        864691128455135232]])

Compute the inverse of a matrix.

In [13]:
import numpy as np
arr = [[1,2],[3,4]]
np.linalg.inv(arr)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

It changes the shape of an array but number of elements remains the same.

In [14]:
import numpy as np
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(f"Shape of array : {arr.shape}")
print(arr)
arr_reshaped = arr.reshape(2,6)
print(f"Shape of reshaped array : {arr_reshaped.shape}")
print(arr_reshaped)

Shape of array : (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of reshaped array : (2, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


1. Concept:
- Broadcasting allows smaller arrays to be “stretched” or “broadcast” across larger arrays to make their shapes compatible.
- It enables vectorized array operations, avoiding unnecessary data copies and improving efficiently.
2. Scalar Broadcasting:
- When combining an array with a scalar value, the scalar is virtually stretched to match the array’s shape.
3. General Broadcasting Rules:
- NumPy compares array shapes element-wise, starting from the trailing dimensions.
- Two dimensions are compatible if they are equal or one of them is 1.
- Missing dimensions are assumed to have size one.